# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d31dc505cea97d07fadbebff933f85944b531d74fcdf4be1face7fa2ecf76c5c0a930c0180b5f78263d6f9a4e75ad56f632b37b769fae78c9228b3f10290b54

test:
  secret_key_base: 5d94146848de2d03cddbd0db377953d324045f11a38cb12452ce58eba769cfc316490bb03cfb523c3f47d22a356b5f307ea7006f41555f48c146f7ed87e6b0ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
